on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    # Maybe at some point we should switch to vx.y.z or release/x.y.z tag names?
      - '?.?.*'

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install ARM toolchain
        run: make arm_sdk_install
      - name: Build targets
        run: make -j8
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: INAV ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
      - name: Upload release assets
        id: upload-release-asset
        uses: csexton/release-asset-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: "obj/*.hex"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
